# .devcontainer/docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c "npm run start"
    ports:
      - "8000:8000"
      - "5173:5173"
    volumes:
      - .:/workspace
